POST http://localhost:5000/api/courses/
Content-Type: application/json

{
    "name":"ch"
}

###

PUT http://localhost:3000/api/courses/3
Content-Type: application/json

{
    "name":"Christian"
}
###

DELETE http://localhost:3000/api/courses/1
Content-Type: application/json


